# Generated by Django 5.0.3 on 2024-04-29 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200, null=True)),
                ('lname', models.CharField(max_length=200, null=True)),
                ('photo', models.ImageField(default='Download_User_Profile_Icon_for_free-removebg-preview.png', upload_to='profiles')),
                ('bdate', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=6)),
                ('city', models.CharField(choices=[('Homs', 'Homs')], default='Homs', max_length=50)),
                ('home_address', models.CharField(choices=[('AlGhoota', 'AlGhoota'), ('AlHamra', 'AlHamra'), ('AlWa3r', 'AlWa3r'), ('Alinshaat', 'Alinshaat'), ('Alhadara', 'Alhadara')], max_length=50, null=True)),
                ('phone', models.CharField(max_length=50)),
                ('is_craftsman', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profile',
            },
        ),
    ]
