# Generated by Django 5.0.3 on 2024-05-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='default.jfif', upload_to='images/profiles/'),
        ),
    ]
