# Generated by Django 5.0.3 on 2024-05-03 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_delete_profile'),
        ('users', '0016_alter_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('work_from', models.TimeField()),
                ('work_to', models.TimeField()),
                ('price_from', models.DecimalField(decimal_places=2, max_digits=7)),
                ('price_to', models.DecimalField(decimal_places=2, max_digits=7)),
                ('work_address', models.CharField(choices=[('AlGhoota', 'AlGhoota'), ('AlHamra', 'AlHamra'), ('AlWa3r', 'AlWa3r'), ('Alinshaat', 'Alinshaat'), ('Alhadara', 'Alhadara')], max_length=50, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=2)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
        ),
    ]
