# Generated by Django 5.0.3 on 2024-05-03 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_provider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='profile',
            new_name='provider',
        ),
    ]
