# Generated by Django 5.0.3 on 2024-05-03 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_rename_profile_provider_provider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'verbose_name': 'provider'},
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='provider',
            new_name='profile',
        ),
    ]
