# Generated by Django 5.0.3 on 2024-05-03 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_delete_profile'),
        ('users', '0019_alter_provider_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='price_from',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='price_to',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
        migrations.AddField(
            model_name='profile',
            name='work_address',
            field=models.CharField(choices=[('AlGhoota', 'AlGhoota'), ('AlHamra', 'AlHamra'), ('AlWa3r', 'AlWa3r'), ('Alinshaat', 'Alinshaat'), ('Alhadara', 'Alhadara')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='work_from',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='work_to',
            field=models.TimeField(null=True),
        ),
        migrations.DeleteModel(
            name='Provider',
        ),
    ]
