# Generated by Django 5.0.6 on 2024-05-24 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rate',
        ),
    ]
