# Generated by Django 5.0.6 on 2024-06-06 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_remove_profile_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='users_favourite',
        ),
        migrations.CreateModel(
            name='Fav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav_by', to='users.profile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favs', to='users.profile')),
            ],
        ),
    ]
