# Generated by Django 5.0.6 on 2024-06-10 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_remove_profile_users_favourite_fav'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fav',
            options={'verbose_name': 'Favourite'},
        ),
        migrations.AlterField(
            model_name='fav',
            name='fav_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav_profile', to='users.profile'),
        ),
    ]
