# Generated by Django 5.0.6 on 2024-06-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alter_profile_price_from_alter_profile_price_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_favorited',
            field=models.BooleanField(default=False),
        ),
    ]
