# Generated by Django 5.0.6 on 2024-08-22 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_remove_profile_is_favorited'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(choices=[(1, '1 star'), (2, '2 star'), (3, '3 star'), (4, '4 star'), (5, '5 star')])),
                ('comment', models.TextField()),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revs', to='users.profile')),
                ('rev_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rev_profile', to='users.profile')),
            ],
            options={
                'unique_together': {('profile', 'rev_profile')},
            },
        ),
    ]
