# Generated by Django 5.0.6 on 2024-08-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_rename_rate_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
