# Generated by Django 5.0.6 on 2024-08-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_alter_review_created_alter_review_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='profile_fname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='profile_lname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='profile_username',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='rev_profile_fname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='rev_profile_lname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='rev_profile_username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
