# Generated by Django 5.0.6 on 2024-08-22 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_review_profile_fname_review_profile_lname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revs', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rev_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rev_profile', to='users.profile'),
        ),
    ]
