# Generated by Django 5.0.6 on 2024-08-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_alter_review_profile_alter_review_rev_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Review'},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='review',
            name='hating_users',
            field=models.ManyToManyField(related_name='hating_profiles', to='users.profile'),
        ),
        migrations.AddField(
            model_name='review',
            name='hatings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='liking_users',
            field=models.ManyToManyField(related_name='liking_profiles', to='users.profile'),
        ),
        migrations.AddField(
            model_name='review',
            name='likings',
            field=models.IntegerField(default=0),
        ),
    ]
