# Generated by Django 5.0.3 on 2024-04-26 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_service_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'service'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='cost_domain',
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200, null=True)),
                ('lname', models.CharField(max_length=200, null=True)),
                ('bdate', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=6, null=True)),
                ('city', models.CharField(choices=[('Homs', 'Homs')], default='Homs', max_length=50)),
                ('home_add', models.CharField(choices=[('AlGhoota', 'AlGhoota'), ('AlHamra', 'AlHamra'), ('AlWa3r', 'AlWa3r'), ('Alinshaat', 'Alinshaat'), ('Alhadara', 'Alhadara')], max_length=50, null=True)),
                ('phone', models.CharField(max_length=50)),
                ('is_craftsman', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'customer',
            },
        ),
    ]
