# Generated by Django 5.0.2 on 2024-04-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_service_options_remove_service_cost_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='photo',
            field=models.ImageField(null=True, upload_to='media\\photos'),
        ),
    ]
