# Generated by Django 5.0.2 on 2024-04-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_customer_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='is_craftsman',
            new_name='craftsman',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='home_add',
            new_name='home_address',
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=6),
        ),
    ]
