# Generated by Django 5.0.3 on 2024-04-29 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_rename_customer_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
