# Generated by Django 5.0.6 on 2024-05-30 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
    ]
