# Generated by Django 5.0.6 on 2024-05-31 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_remove_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(blank=True, choices=[('air conditioning', 'air conditioning'), ('aliminume fitting', 'aliminume fitting'), ('Architecture Engineering', 'Architecture Engineering'), ('Blacksmith', 'Blacksmith'), ('carpenters', 'carpenters'), ('Ceramics and tiling', 'Ceramics and tiling'), ('decorations', 'decorations'), ('Civil Engineering', 'Civil Engineering'), ('electrician', 'electrician'), ('glass', 'glass'), ('house painting', 'house painting'), ('movers', 'movers'), ('plumbers', 'plumbers'), ('Roof insulation', 'Roof insulation'), ('solar energy', 'solar energy'), ('Central gas installations', 'Central gas installations')], max_length=50, null=True),
        ),
    ]
