# Generated by Django 5.0.6 on 2024-06-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_alter_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(blank=True, choices=[('air conditioning', 'air conditioning'), ('Architecture Engineering', 'Architecture Engineering'), ('carpenters', 'carpenters'), ('Ceramics and tiling', 'Ceramics and tiling'), ('decorations', 'decorations'), ('Civil Engineering', 'Civil Engineering'), ('electrician', 'electrician'), ('house painting', 'house painting'), ('movers', 'movers'), ('plumbers', 'plumbers'), ('Roof insulation', 'Roof insulation'), ('solar energy', 'solar energy')], max_length=50, null=True),
        ),
    ]
