# Generated by Django 5.0.6 on 2024-06-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_customer_alter_booking_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_username',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='provider_username',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
