# Generated by Django 5.0.6 on 2024-08-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_customer_username_booking_provider_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_fname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_lname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
